from supertonic import TTS
import numpy as np

tts = TTS(auto_download=True)
style = tts.get_voice_style(voice_name="M1")

# text = "A gentle breeze moved through the open window while everyone listened to the story."
# text = "Hello, Bay Area K group Vibe coding members. This is generated by Supertonic model on my local machine"
text = "To clarify if this model is locally inferenced, I turned off wifi and generated this audio"
wav, duration = tts.synthesize(text, voice_style=style, lang="en")

tts.save_audio(wav, "output3.wav")
duration_sec = float(np.asarray(duration).reshape(-1)[0])
print(f"Generated {duration_sec:.2f}s of audio")
